services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./packages/frontend
      target: production
    env_file:
      - ./packages/frontend/.env
    volumes:
      - ./packages/frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 81:80
  backend:
    build:
      dockerfile: Dockerfile
      context: ./packages/backend
      target: production
    command: npm run start:prod
    env_file:
      - ./packages/backend/.env
    environment:
      POSTGRES_HOST: db
    volumes:
      - ./packages/backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - db
  db:
    image: postgres:14
    restart: always
    env_file:
      - packages/backend/.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./db/pgData:/var/lib/postgresql/data